In [71]:
import numpy as np
import pandas as pd
df=pd.read_csv("C:\\Users\\vanar\\Downloads\\archivee\\insurance.csv")
df.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [72]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [73]:
df['sex'] = df['sex'].replace(['male', 'female'], [1, 0])
df['smoker'] = df['smoker'].replace(['yes', 'no'], [1, 0])
df['region'] = df['region'].replace(['northeast', 'southeast','northwest', 'southwest'], [0,1,2,3])
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       1   1725.55230
2   28    1  33.000         3       0       1   4449.46200
3   33    1  22.705         0       0       2  21984.47061
4   32    1  28.880         0       0       2   3866.85520

In [74]:
# svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
X = df.drop(columns=['charges'])
y = df['charges']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
svm_model = SVR(kernel='linear', C=1.0)
svm_model.fit(X_train_scaled, y_train)
y_pred = svm_model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 152098996.4650521


In [75]:
# linear regression
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
y_pred = linear_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R-squared Score:", r2)

Mean Squared Error: 33927609.017121345
R-squared Score: 0.7814628906071343


In [76]:
linear_model.predict([[19,0,27.900,0,1,3]])

C:\Users\vanar\anaconda3\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([25209.26035664])

In [77]:
linear_model.predict([[18,1,33.770,1,0,1]])

C:\Users\vanar\anaconda3\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4094.16047678])

In [78]:
#xgboost
import xgboost as xgb
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.9, learning_rate = 0.2, max_depth = 5, alpha = 10, n_estimators = 49)
xg_reg.fit(X_train, y_train)
y_pred = xg_reg.predict(X_test)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print("RMSE:", rmse)

RMSE: 4444.571976108938


In [79]:
xg_reg.predict([[18,1,33.770,1,0,1]])

array([2953.1885], dtype=float32)

In [69]:
xg_reg.predict([[19,0,27.900,0,1,3]])

array([17196.205], dtype=float32)

In [80]:
xg_reg.predict([[28,1,33.000,3,0,1]])

array([6480.749], dtype=float32)

In [81]:
import pickle
with open("xg_bicp.pkl","wb") as file:
    pickle.dump(xg_reg,file)